# Generated by Django 5.2.7 on 2025-10-23 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('Mr', 'Mr'), ('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Miss', 'Miss'), ('Dr', 'Dr'), ('Prof', 'Prof')], max_length=10, null=True)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('persal_number', models.CharField(max_length=8, unique=True)),
                ('mobile_number', models.CharField(blank=True, max_length=10, null=True)),
                ('district', models.CharField(max_length=100)),
                ('local_municipality', models.CharField(blank=True, max_length=100, null=True)),
                ('facility', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
