# Generated by Django 5.2.7 on 2025-10-11 20:06
# accounts/migrations/0002_create_groups.py
from django.db import migrations

def create_user_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Admin')
    Group.objects.get_or_create(name='User')

class Migration(migrations.Migration):
    
    dependencies = [
        ('accounts', '0001_initial'), # This ensures the Profile table is created FIRST.
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]