# Generated by Django 5.2.7 on 2025-10-23 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=100)),
                ('local_municipality', models.CharField(max_length=100)),
                ('facility', models.CharField(max_length=100)),
                ('facility_type', models.CharField(max_length=100)),
                ('report_date', models.CharField(max_length=50)),
                ('time_slot', models.CharField(max_length=50)),
                ('no_births_to_report', models.BooleanField(default=False, verbose_name='No Births to Report')),
                ('born_before_arrival', models.BooleanField(default=False, verbose_name='Born Before Arrival (BBA)')),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_surname', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_dob', models.DateField(blank=True, null=True, verbose_name="Mother's D.O.B.")),
                ('birth_mode', models.CharField(blank=True, max_length=100, null=True)),
                ('gravidity', models.PositiveIntegerField(blank=True, null=True)),
                ('parity', models.PositiveIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('weight', models.PositiveIntegerField(blank=True, help_text='Weight in grams', null=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='babies', to='births.delivery')),
            ],
        ),
    ]
