LOCATION_DATA = {
    "municipalities": {
        "Alfred Nzo DM": ["Matatiele LM", "Umzimvubu LM", "Mbizana LM", "Ntabankulu LM"],
        "Amathole DM": ["Mbhashe LM", "Raymond Mhlaba LM", "Amahlathi LM", "Mnquma LM", "Great Kei LM", "Ngqushwa LM"],
        "Buffalo City MM": ['Buffalo City SD'],
        "Chris Hani DM": ["Emalahleni LM", "Inxuba Yethemba LM", "Enoch Mgijima LM", "Engcobo LM", "Sakhisizwe LM", "Intsika Yethu LM"],
        "Joe Qabi DM": ["Walter Sisulu LM", "Elundini LM", "Senqu LM"],
        "Nelson Mandela MM": ["N Mandela B SD", "N Mandela C SD", "N Mandela A SD"],
        "OR Tambo DM": ["Nyandeni LM", "Ingquza Hill LM", "Mhlontlo LM", "King Sabata Dalindyebo LM", "Port St Johns LM"],
        "Sarah Baartman DM": ["Makana LM", "Blue Crane Route LM", "Ndlambe LM", "Dr B Naudé LM", "Sundays River Valley LM", "Kou-Kamma LM", "Kouga LM"]
    },
    "facilities": {
          "Matatiele LM":["Maluti CHC","Tayler Bequest Hospital (Matatiele)"],  
          "Mbizana LM":["Greenville Hospital", "St Patrick's Hospital"],  
          "Ntabankulu LM":["Sipetu Hospital","Tabankulu CHC"],  
          "Umzimvubu LM":["Madzikane Ka Zulu Memorial Hospital","Mount Ayliff Hospital"], 
          "Amahlathi LM":["Cathcart Hospital","SS Gida Hospital","Stutterheim Hospital"], 
          "Great Kei LM":["Komga Hospital"],  
          "Mbhashe LM":["Idutywa Village CHC", "Madwaleni Hospital", "Willowvale CHC","Xhora CHC"], 
          "Mnquma LM":["Butterworth Hospital","Nqamakwe CHC","Tafalofefe Hospital"],
          "Ngqushwa LM":["Nompumelelo (Peddie) Hospital"],
          "Raymond Mhlaba LM":["Adelaide Hospital", "Bedford Hospital", "Fort Beaufort Hospital","Middledrift CHC","Victoria Hospital"],  
          "Buffalo City SD":["Bhisho Hospital","Cecilia Makiwane Hospital","Dimbaza CHC","Duncan Village CHC","Empilweni Gompo CHC","Frere Hospital","Nontyatyambo CHC"],
          "Emalahleni LM":["Dordrecht Hospital",  "Glen Grey Hospital","Indwe Hospital","Ngonyama CHC"],
          "Engcobo LM":["All Saints Hospital","Mjanyana Hospital","Ngcobo CHC", "Zwelakhe Dalasile CHC"
          ],
          "Enoch Mgijima LM":["Care Cure Queenstown Hospital","Frontier Hospital","Hewu Hospital", "Ilinge Clinic","Life Queenstown Prv Hosp","Martje Venter (Tarkastad) Hospital","Molteno Hospital","Nomzamo CHC","Sterkstroom Hospital","Thornhill CHC","Whittlesea CHC"],  
          "Intsika Yethu LM":["Cofimvaba Hospital","Kuyasa CHC"], 
          "Inxuba Yethemba LM":["Cradock Hospital","Wilhelm Stahl (Middelburg) Hospital"],  
          "Sakhisizwe LM":["Cala Hospital","Elliot Hospital"],  
          "Elundini LM":["Maclear Hospital","Taylor Bequest Hospital (Elundini)"],  
          "Senqu LM":["Cloete Joubert (Barkly East) Hospital","Empilisweni Hospital","Lady Grey Hospital","Umlamli Hospital"],  
          "Walter Sisulu LM":["Aliwal North Hospital","Burgersdorp Hospital","Jamestown Hospital","St Francis Hospital","Steynsburg Hospital"], 
          "N Mandela A SD":["Dora Nginza Hospital","Kwazakhele CHC","Motherwell CHC"],  
          "N Mandela B SD":["Laetitia Bam CHC","Netcare Cuyler Hosp","Rosedale CHC","Uitenhage Hospital"],  
          "N Mandela C SD":["Central CHC (Sandford)","Gqebera CHC","Korsten CHC","Life Mercantile Hospital","Life St George's Hosp","Livingstone Hospital", "Netcare Greenacres Hosp","New Brighton CHC","Port Elizabeth Provincial Hospital","West End CHC","Westways Hosp"],
            
          "Ingquza Hill LM":["Flagstaff CHC","Holy Cross Hospital","St Elizabeth's Hospital","Lusikisiki Village Clinic"],  
          "King Sabata Dalindyebo LM":["Baziya CHC","Canzibe Hospital","Crossmed Mthatha Private Hospital","Life St Mary's Hosp","Mbekweni CHC","Mqanduli CHC","Mthatha General Hospital","Nelson Mandela Academic Hospital","Ngangelizwe CHC","Ngcwanguba CHC","Zithulele Hospital"],  
          "Mhlontlo LM":["Dr Malizo Mpehle Memorial Hospital",  "Isilimela Hospital","Mhlakulo CHC","Nessie Knight Hospital","Qumbu CHC"],  
          "Nyandeni LM":["Canzibe Hospital","Makhotyana CHC","St Barnabas Hospital"], 
          "Port St Johns LM":["Bambisana Hospital","Isilimela Hospital","Port St Johns CHC","Tombo CHC"], 
          "Blue Crane Route LM":["Andries Vosloo Hospital"],  
          "Dr B Naudé LM":["Aberdeen Hospital", "Graaff-Reinet Day Hospital","Midland Hospital","SAWAS Memorial (Jansenville) Hospital","Willowmore Hospital"], 
          "Kouga LM":["Humansdorp Hospital"], 
          "Kou-Kamma LM":["BJ Vorster (Kareedouw) Hospital","Joubertina CHC"],  
          "Makana LM":["Settlers Day Hospital CHC","Settlers Hospital"],  
          "Ndlambe LM":["Port Alfred Hospital"],  
          "Sundays River Valley LM":["Sundays Valley (Kirkwood) Hospital"]

    }
}

DISTRICT_CHOICES = [
    ("", "--Select District--"),
    ("Alfred Nzo DM", "Alfred Nzo DM"),
    ("Amathole DM", "Amathole DM"),
    ("Buffalo City MM", "Buffalo City MM"),
    ("Chris Hani DM", "Chris Hani DM"),
    ("Joe Qabi DM", "Joe Qabi DM"),
    ("Nelson Mandela MM", "Nelson Mandela MM"),
    ("OR Tambo DM", "OR Tambo DM"),
    ("Sarah Baartman DM", "Sarah Baartman DM"),
]

FACILITY_TYPES = {
    "Aberdeen Hospital": "District Hospital",
    "Adelaide Hospital": "District Hospital",
    "Aliwal North Hospital": "District Hospital",
    "All Saints Hospital": "District Hospital",
    "Andries Vosloo Hospital": "District Hospital",
    "Bambisana Hospital": "District Hospital",
    "Baziya CHC": "CHC",
    "Bhisho Hospital": "District Hospital",
    "BJ Vorster (Kareedouw) Hospital": "District Hospital",
    "Burgersdorp Hospital": "District Hospital",
    "Butterworth Hospital": "District Hospital",
    "Cala Hospital": "District Hospital",
    "Canzibe Hospital": "District Hospital",
    "Cathcart Hospital": "District Hospital",
    "Cecilia Makiwane Hospital": "Regional Hospital",
    "Cloete Joubert (Barkly East) Hospital": "District Hospital",
    "Cofimvaba Hospital": "District Hospital",
    "Cradock Hospital": "District Hospital",
    "Dimbaza CHC": "CHC",
    "Dora Nginza Hospital": "Regional Hospital",
    "Dordrecht Hospital": "District Hospital",
    "Dr Malizo Mpehle Memorial Hospital": "District Hospital",
    "Duncan Village CHC": "CHC",
    "Elliot Hospital": "District Hospital",
    "Empilisweni Hospital": "District Hospital",
    "Empilweni Gompo CHC": "CHC",
    "Flagstaff CHC": "CHC",
    "Fort Beaufort Hospital": "District Hospital",
    "Frere Hospital": "Tertiary Hospital",
    "Frontier Hospital": "Regional Hospital",
    "Glen Grey Hospital": "District Hospital",
    "Greenville Hospital": "District Hospital",
    "Hewu Hospital": "District Hospital",
    "Holy Cross Hospital": "District Hospital",
    "Humansdorp Hospital": "District Hospital",
    "Idutywa Village CHC": "CHC",
    "Indwe Hospital": "District Hospital",
    "Ilinge Clinic": "Clinic",
    "Isilimela Hospital": "District Hospital",
    "Jamestown Hospital": "District Hospital",
    "Joubertina CHC": "CHC",
    "Komga Hospital": "District Hospital",
    "Korsten CHC": "CHC",
    "Kuyasa CHC": "CHC",
    "Kwazakhele CHC": "CHC",
    "Lady Grey Hospital": "District Hospital",
    "Laetitia Bam CHC": "CHC",
    "Life Mercantile Hospital": "Private Hospital",
    "Life St George's Hosp": "Private Hospital",
    "Livingstone Hospital": "Tertiary Hospital",
    "Lusikisiki Village Clinic": "Clinic",
    "Maclear Hospital": "District Hospital",
    "Madwaleni Hospital": "District Hospital",
    "Madzikane Ka Zulu Memorial Hospital": "District Hospital",
    "Makhotyana CHC": "CHC",
    "Maluti CHC": "CHC",
    "Martje Venter (Tarkastad) Hospital": "District Hospital",
    "Mbekweni CHC": "CHC",
    "Mhlakulo CHC": "CHC",
    "Midland Hospital": "District Hospital",
    "Molteno Hospital": "District Hospital",
    "Motherwell CHC": "CHC",
    "Mount Ayliff Hospital": "District Hospital",
    "Mqanduli CHC": "CHC",
    "Mthatha General Hospital": "Regional Hospital",
    "Nelson Mandela Academic Hospital": "Academic Hospital",
    "Nessie Knight Hospital": "District Hospital",
    "Netcare Cuyler Hosp": "Private Hospital",
    "Netcare Greenacres Hosp": "Private Hospital",
    "Ngangelizwe CHC": "CHC",
    "Ngcwanguba CHC": "CHC",
    "Ngonyama CHC": "CHC",
    "Nompumelelo (Peddie) Hospital": "District Hospital",
    "Nontyatyambo CHC": "CHC",
    "Nqamakwe CHC": "CHC",
    "Port Alfred Hospital": "District Hospital",
    "Port St Johns CHC": "CHC", 
    "SAWAS Memorial (Jansenville) Hospital": "District Hospital",
    "Settlers Hospital": "District Hospital",
    "Sipetu Hospital": "District Hospital",
    "SS Gida Hospital": "District Hospital",
    "St Barnabas Hospital": "District Hospital",
    "St Elizabeth's Hospital": "Regional Hospital",
    "St Patrick's Hospital": "District Hospital",
    "Sterkstroom Hospital": "District Hospital",
    "Steynsburg Hospital": "District Hospital",
    "Stutterheim Hospital": "District Hospital",
    "Sundays Valley (Kirkwood) Hospital": "District Hospital",
    "Tabankulu CHC": "CHC",
    "Tafalofefe Hospital": "District Hospital",
    "Tayler Bequest Hospital (Matatiele)": "District Hospital",
    "Taylor Bequest Hospital (Elundini)": "District Hospital",
    "Thornhill CHC": "CHC",
    "Uitenhage Hospital": "District Hospital",
    "Umlamli Hospital": "District Hospital",
    "Victoria Hospital": "District Hospital",
    "West End CHC": "CHC",
    "Whittlesea CHC": "CHC",
    "Wilhelm Stahl (Middelburg) Hospital": "District Hospital",
    "Willowmore Hospital": "District Hospital",
    "Willowvale CHC": "CHC",
    "Zithulele Hospital": "District Hospital",
    "Zwelakhe Dalasile CHC": "CHC",
}